### ISSUE TITLE
Web nefukční, končí to točícím se kolečkem.

### ISSUE THREAD

**Issue by ghost** [Zemistr/stream-video-downloader#1]
Ahoj =)
- Aktuální verze končí chybou v konzoli. `Uncaught TypeError: Cannot set property 'onclick' of null`
  - Browser: _Chromium 51.0.2704.79 Ubuntu 16.04_
- Funkční verze: `git checkut 5a5dff1527dce50eaa93088f21faa24ce3500f2f`

Btw díky za poslední symfony sraz, byl fajn.

**Comment by Zemistr** [comment]
Ahoj, díky za zprávu, omrknu to :smiley: 
Jo za sraz nemáš zač :wink:

**Comment by Zemistr** [comment]
Opraveno, děkuji za info! :wink:
